# Generated by ChatGPT: GPT-5 Thinking Mini on 11/14/25 3:19 pm
# https://chatgpt.com/share/6917b8bb-f1b0-8008-93b8-9559d112117d
# "In-place quicksort using Lomuto partition"
from typing import List

def lomuto_partition(a: List[int], lo: int, hi: int) -> int:
    pivot = a[hi]
    i = lo
    for j in range(lo, hi):
        if a[j] < pivot:
            a[i], a[j] = a[j], a[i]
            i += 1
    a[i], a[hi] = a[hi], a[i]
    return i

def quicksort_inplace(a: List[int], lo: int = 0, hi: int | None = None) -> None:
    """Sort list 'a' in-place. Call with quicksort_inplace(a)."""
    if hi is None:
        hi = len(a) - 1
    if lo < hi:
        p = lomuto_partition(a, lo, hi)
        quicksort_inplace(a, lo, p - 1)
        quicksort_inplace(a, p + 1, hi)

# Example
if __name__ == "__main__":
    arr = [3,6,8,10,1,2,1]
    quicksort_inplace(arr)
    print(arr)  # [1,1,2,3,6,8,10]
