# Generated by Claude: Sonnet 4.5 on 11/14/2025 3:29 pm
# https://claude.ai/share/b53b6b55-84cc-4bcd-b22a-6b251d68033d
def quicksort(arr):
    """
    Sorts an array using the quicksort algorithm.
    
    Args:
        arr: List of comparable elements to sort
        
    Returns:
        Sorted list
    """
    # Base case: arrays with 0 or 1 element are already sorted
    if len(arr) <= 1:
        return arr
    
    # Choose pivot (using middle element for better average performance)
    pivot = arr[len(arr) // 2]
    
    # Partition array into three parts
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    
    # Recursively sort left and right partitions
    return quicksort(left) + middle + quicksort(right)


# Example usage
if __name__ == "__main__":
    # Test with various arrays
    test_cases = [
        [64, 34, 25, 12, 22, 11, 90],
        [5, 2, 8, 1, 9],
        [1],
        [],
        [3, 3, 3, 3],
        [-5, 10, -3, 0, 8, -1]
    ]
    
    for arr in test_cases:
        print(f"Original: {arr}")
        print(f"Sorted:   {quicksort(arr)}")
        print()