# Generated by DeepSeek: V3.2 on 11/14/25 3:51 pm
# https://chat.deepseek.com/share/4sftothc85crjomtqv

def quicksort(arr):
    """
    Sorts an array using the quicksort algorithm.
    
    Args:
        arr: List of comparable elements
        
    Returns:
        Sorted list
    """
    if len(arr) <= 1:
        return arr
    
    pivot = arr[len(arr) // 2]  # Choose middle element as pivot
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    
    return quicksort(left) + middle + quicksort(right)



# Example usage
if __name__ == "__main__":
    # Test the quicksort implementations
    test_array = [64, 34, 25, 12, 22, 11, 90, 5]
    
    print("Original array:", test_array)
    
    # Using the simple version
    sorted_array = quicksort(test_array.copy())
    print("Sorted (simple version):", sorted_array)