# Generated by ChatGPT: GPT-5 Thinking Mini on 12/2/25 5:57 pm
# https://chatgpt.com/share/692f9909-0c00-8008-a85d-3d3ca43d83de
def quicksort(a: list[int]) -> None:
    def _qs(lo: int, hi: int) -> None:
        if lo >= hi:
            return
        
        pivot = a[(lo + hi) // 2]
        i = lo
        j = hi
        
        while True:
            while a[i] < pivot:
                i += 1
            while a[j] > pivot:
                j -= 1
            
            if i >= j:
                break
            
            a[i], a[j] = a[j], a[i]
            i += 1
            j -= 1
        
        _qs(lo, j)
        _qs(j + 1, hi)
    
    _qs(0, len(a) - 1)