# Generated by Google Gemini: 2.5 Pro on 12/2/25 6:01 pm
# https://gemini.google.com/share/5869e0ff5217
def quicksort(a: list[int]) -> None:
    stack = [(0, len(a) - 1)]
    while stack:
        low, high = stack.pop()
        if low < high:
            pivot = a[high]
            i = low - 1
            for j in range(low, high):
                if a[j] <= pivot:
                    i += 1
                    a[i], a[j] = a[j], a[i]
            a[i + 1], a[high] = a[high], a[i + 1]
            p = i + 1
            stack.append((low, p - 1))
            stack.append((p + 1, high))