# Generated by Google Gemini: 2.5 Pro on 11/29/25 9:16 pm
# https://gemini.google.com/share/98d648337780
def quicksort(a: list[int]) -> None:
    def _helper(low, high):
        if low < high:
            pivot = a[high]
            i = low - 1
            for j in range(low, high):
                if a[j] <= pivot:
                    i += 1
                    a[i], a[j] = a[j], a[i]
            a[i + 1], a[high] = a[high], a[i + 1]
            pi = i + 1
            _helper(low, pi - 1)
            _helper(pi + 1, high)
    _helper(0, len(a) - 1)