# Generated by DeepSeek: V3.2 on 11/29/25 9:13 pm
# https://chat.deepseek.com/share/5tcbyf07f2qpfj89mo
def quicksort(a: list[int]) -> None:
    def _quicksort(low, high):
        if low < high:
            pivot_index = partition(low, high)
            _quicksort(low, pivot_index - 1)
            _quicksort(pivot_index + 1, high)
    
    def partition(low, high):
        pivot = a[high]
        i = low - 1
        for j in range(low, high):
            if a[j] <= pivot:
                i += 1
                a[i], a[j] = a[j], a[i]
        a[i + 1], a[high] = a[high], a[i + 1]
        return i + 1
    
    if a:
        _quicksort(0, len(a) - 1)