// Generated by DeepSeek: V3.2 on 12/4/25 9:42 pm
// https://chat.deepseek.com/share/g2p7r6kjkvigcxfhlg
use std::collections::{HashMap, BinaryHeap};
use std::cmp::Ordering;

pub type Node = usize;
pub type Weight = f64;
pub type Graph = HashMap<Node, Vec<(Node, Weight)>>;

// Internal struct for heap entries
#[derive(PartialEq)]
struct HeapEntry {
    node: Node,
    distance: Weight,
}

impl Eq for HeapEntry {}

impl PartialOrd for HeapEntry {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        // Reverse comparison for min-heap (smaller distance = higher priority)
        other.distance.partial_cmp(&self.distance)
    }
}

impl Ord for HeapEntry {
    fn cmp(&self, other: &Self) -> Ordering {
        // Use total_cmp for f64 to get a total ordering (safe for non-negative weights)
        self.partial_cmp(other).unwrap_or(Ordering::Equal)
    }
}

pub fn dijkstra(graph: &Graph, source: Node) -> HashMap<Node, Weight> {
    let mut distances = HashMap::new();
    let mut heap = BinaryHeap::new();
    
    // Initialize with source node
    distances.insert(source, 0.0);
    heap.push(HeapEntry {
        node: source,
        distance: 0.0,
    });
    
    while let Some(HeapEntry { node: current, distance: current_dist }) = heap.pop() {
        // Skip if we found a better path already
        if let Some(&best) = distances.get(&current) {
            if current_dist > best {
                continue;
            }
        }
        
        // Explore neighbors
        if let Some(neighbors) = graph.get(&current) {
            for &(neighbor, weight) in neighbors {
                let new_dist = current_dist + weight;
                
                // Update distance if we found a shorter path
                let should_update = match distances.get(&neighbor) {
                    Some(&existing) => new_dist < existing,
                    None => true,
                };
                
                if should_update {
                    distances.insert(neighbor, new_dist);
                    heap.push(HeapEntry {
                        node: neighbor,
                        distance: new_dist,
                    });
                }
            }
        }
    }
    
    distances
}