# Generated by Google Gemini: 2.5 Pro on 11/29/25 9:16 pm
# https://gemini.google.com/share/98d648337780
def quicksort(a: list[int]) -> None:
    def _helper(low, high):
        while low < high:
            mid = (low + high) // 2
            if a[mid] < a[low]:
                a[low], a[mid] = a[mid], a[low]
            if a[high] < a[low]:
                a[low], a[high] = a[high], a[low]
            if a[mid] < a[high]:
                a[mid], a[high] = a[high], a[mid]
            pivot = a[high]
            i = low - 1
            for j in range(low, high):
                if a[j] < pivot:
                    i += 1
                    a[i], a[j] = a[j], a[i]
            a[i + 1], a[high] = a[high], a[i + 1]
            p = i + 1
            if p - low < high - p:
                _helper(low, p - 1)
                low = p + 1
            else:
                _helper(p + 1, high)
                high = p - 1
    _helper(0, len(a) - 1)