# Generated by DeepSeek: V3.2 on 11/29/25 9:13 pm
# https://chat.deepseek.com/share/5tcbyf07f2qpfj89mo
def quicksort(a: list[int]) -> None:
    def _quicksort(low, high):
        while low < high:
            pivot_index = partition(low, high)
            if pivot_index - low < high - pivot_index:
                _quicksort(low, pivot_index - 1)
                low = pivot_index + 1
            else:
                _quicksort(pivot_index + 1, high)
                high = pivot_index - 1
    
    def partition(low, high):
        mid = low + (high - low) // 2
        if a[low] > a[mid]:
            a[low], a[mid] = a[mid], a[low]
        if a[low] > a[high]:
            a[low], a[high] = a[high], a[low]
        if a[mid] > a[high]:
            a[mid], a[high] = a[high], a[mid]
        pivot = a[mid]
        a[mid], a[high - 1] = a[high - 1], a[mid]
        i = low
        j = high - 1
        while True:
            i += 1
            while a[i] < pivot:
                i += 1
            j -= 1
            while a[j] > pivot:
                j -= 1
            if i >= j:
                break
            a[i], a[j] = a[j], a[i]
        a[i], a[high - 1] = a[high - 1], a[i]
        return i
    
    if len(a) <= 1:
        return
    _quicksort(0, len(a) - 1)