# Generated by ChatGPT: GPT-5 Thinking Mini on 12/2/25 5:22 pm
# https://chatgpt.com/share/692f90f9-1acc-8008-8f61-2ee294d42ba0
def quicksort(a: list[int]) -> None:
    if len(a) < 2:
        return

    def _qs(lo: int, hi: int) -> None:
        if lo >= hi:
            return
        
        pivot = a[(lo + hi) // 2]
        i, j = lo, hi
        
        while True:
            while a[i] < pivot:
                i += 1
            while a[j] > pivot:
                j -= 1
            if i >= j:
                p = j
                break
            a[i], a[j] = a[j], a[i]
            i += 1
            j -= 1
        
        _qs(lo, p)
        _qs(p + 1, hi)
    
    _qs(0, len(a) - 1)