# Generated by DeepSeek: V3.2 on 12/2/25 5:45 pm
# https://chat.deepseek.com/share/hr9czkptes0kp04vzo
def quicksort(a: list[int]) -> None:
    def _quicksort(left: int, right: int) -> None:
        if left >= right:
            return
        
        pivot = a[(left + right) // 2]
        i, j = left, right
        
        while i <= j:
            while a[i] < pivot:
                i += 1
            while a[j] > pivot:
                j -= 1
            if i <= j:
                a[i], a[j] = a[j], a[i]
                i += 1
                j -= 1
        
        _quicksort(left, j)
        _quicksort(i, right)
    
    if len(a) > 1:
        _quicksort(0, len(a) - 1)