# Generated by Google Gemini: 2.5 Pro on 12/2/25 5:40 pm
# https://gemini.google.com/share/20324216c0d5
def quicksort(a: list[int]) -> None:
    def _partition(arr, low, high):
        pivot = arr[high]
        i = low - 1
        for j in range(low, high):
            if arr[j] <= pivot:
                i += 1
                arr[i], arr[j] = arr[j], arr[i]
        arr[i + 1], arr[high] = arr[high], arr[i + 1]
        return i + 1

    def _quick_sort_recursive(arr, low, high):
        if low < high:
            pi = _partition(arr, low, high)
            _quick_sort_recursive(arr, low, pi - 1)
            _quick_sort_recursive(arr, pi + 1, high)

    _quick_sort_recursive(a, 0, len(a) - 1)