# Generated by Claude: Sonnet 4.5 on 12/2/2025 5:34 pm
# https://claude.ai/share/6b616bc9-fd35-4b5e-8af5-fee4a23e9c29
def quicksort(a: list[int]) -> None:
    def _quicksort(low, high):
        if low < high:
            pivot = a[high]
            i = low - 1
            for j in range(low, high):
                if a[j] <= pivot:
                    i += 1
                    a[i], a[j] = a[j], a[i]
            a[i + 1], a[high] = a[high], a[i + 1]
            pivot_index = i + 1
            _quicksort(low, pivot_index - 1)
            _quicksort(pivot_index + 1, high)
    
    _quicksort(0, len(a) - 1)