// Generated by Claude: Sonnet 4.5 on 12/3/2025 4:31 pm
// https://claude.ai/share/c7331744-c4fc-432b-bb01-c5a303ac9ac1
pub fn quicksort(a: &mut [i32]) {
    if a.len() <= 1 {
        return;
    }
    let pivot_index = partition(a);
    let (left, right) = a.split_at_mut(pivot_index);
    quicksort(left);
    quicksort(&mut right[1..]);
}

fn partition(a: &mut [i32]) -> usize {
    let len = a.len();
    let pivot_index = len / 2;
    a.swap(pivot_index, len - 1);
    let pivot = a[len - 1];
    let mut i = 0;
    for j in 0..len - 1 {
        if a[j] <= pivot {
            a.swap(i, j);
            i += 1;
        }
    }
    a.swap(i, len - 1);
    i
}