// Generated by DeepSeek: V3.2 on 12/3/25 4:27 pm
// https://chat.deepseek.com/share/uf8mcc082nhajqlb7x
pub fn quicksort(a: &mut [i32]) {
    if a.len() <= 1 {
        return;
    }
    
    let p = partition(a);
    quicksort(&mut a[..p]);
    quicksort(&mut a[p + 1..]);
}

fn partition(a: &mut [i32]) -> usize {
    let p = a.len() - 1;
    let mut i = 0;
    
    for j in 0..p {
        if a[j] <= a[p] {
            a.swap(i, j);
            i += 1;
        }
    }
    
    a.swap(i, p);
    i
}