// Generated by ChatGPT: GPT-5 Thinking Mini on 12/3/25 4:26 pm
// https://chatgpt.com/share/6937f51e-c6b4-8008-ba70-89094d81e69e
pub fn quicksort(a: &mut [i32]) {
    fn qs(a: &mut [i32], lo: isize, hi: isize) {
        if lo >= hi {
            return;
        }
        let mut i = lo;
        let mut j = hi;
        let pivot = a[((lo + hi) / 2) as usize];
        while i <= j {
            while i <= j && a[i as usize] < pivot {
                i += 1;
            }
            while i <= j && a[j as usize] > pivot {
                j -= 1;
            }
            if i <= j {
                a.swap(i as usize, j as usize);
                i += 1;
                j -= 1;
            }
        }
        if lo < j {
            qs(a, lo, j);
        }
        if i < hi {
            qs(a, i, hi);
        }
    }
    let len = a.len();
    if len <= 1 {
        return;
    }
    qs(a, 0, (len - 1) as isize);
}