// Generated by Google Gemini: 2.5 Pro on 12/3/25 4:29 pm 
pub fn quicksort(a: &mut [i32]) {
    let len = a.len();
    if len <= 1 {
        return;
    }
    let pivot_index = len / 2;
    a.swap(pivot_index, len - 1);
    let mut i = 0;
    for j in 0..len - 1 {
        if a[j] <= a[len - 1] {
            a.swap(i, j);
            i += 1;
        }
    }
    a.swap(i, len - 1);
    let (left, right) = a.split_at_mut(i);
    quicksort(left);
    quicksort(&mut right[1..]);
}