# Generated by ChatGPT: GPT-5 Thinking Mini on 11/14/25 3:19 pm
# https://chatgpt.com/share/6917b8bb-f1b0-8008-93b8-9559d112117d
# "Functional (concise, not in-place)"
from typing import List

def quicksort_functional(arr: List[int]) -> List[int]:
    """Return a new sorted list (not in-place)."""
    if len(arr) <= 1:
        return arr[:]
    pivot = arr[len(arr) // 2]
    left  = [x for x in arr if x < pivot]
    mid   = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort_functional(left) + mid + quicksort_functional(right)

# Example
if __name__ == "__main__":
    print(quicksort_functional([3,6,8,10,1,2,1]))  # [1,1,2,3,6,8,10]
