# Generated by Google Gemini: 2.5 Pro on 11/14/25 3:34 pm
# https://gemini.google.com/share/373b91bf2f92
def quicksort(arr):
  """
  Sorts a list in ascending order using the Quicksort algorithm.
  """
  if len(arr) <= 1:
    # Base case: A list with 0 or 1 element is already sorted
    return arr
  else:
    # 1. Choose a pivot element
    # We'll use the first element as the pivot.
    pivot = arr[0]
    
    # 2. Partition the list
    # Create two sub-lists: one for elements less than or equal to the pivot,
    # and one for elements greater than the pivot.
    # We use list slicing (arr[1:]) to iterate over elements *other* than the pivot.
    
    less = [x for x in arr[1:] if x <= pivot]
    greater = [x for x in arr[1:] if x > pivot]
    
    # 3. Recurse
    # Recursively sort the sub-lists and combine them with the pivot in the middle.
    return quicksort(less) + [pivot] + quicksort(greater)