# Generated by DeepSeek: V3.2 on 11/14/25 3:51 pm
# https://chat.deepseek.com/share/4sftothc85crjomtqv
# In-place version (more memory efficient)
def quicksort_inplace(arr, low=0, high=None):
    """
    In-place quicksort implementation.
    
    Args:
        arr: List to be sorted
        low: Starting index
        high: Ending index
    """
    if high is None:
        high = len(arr) - 1
    
    if low < high:
        # Partition the array and get the pivot index
        pivot_index = partition(arr, low, high)
        
        # Recursively sort elements before and after partition
        quicksort_inplace(arr, low, pivot_index - 1)
        quicksort_inplace(arr, pivot_index + 1, high)

def partition(arr, low, high):
    """
    Partitions the array around a pivot element.
    
    Args:
        arr: List to partition
        low: Starting index
        high: Ending index
        
    Returns:
        Index of the pivot after partitioning
    """
    # Choose the rightmost element as pivot
    pivot = arr[high]
    
    # Index of smaller element (indicates right position of pivot)
    i = low - 1
    
    for j in range(low, high):
        # If current element is smaller than or equal to pivot
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]  # Swap elements
    
    # Place the pivot in the correct position
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

# Example usage
if __name__ == "__main__":
    # Test the quicksort implementations
    test_array = [64, 34, 25, 12, 22, 11, 90, 5]
    
    print("Original array:", test_array)
    
    # Using the in-place version
    inplace_array = test_array.copy()
    quicksort_inplace(inplace_array)
    print("Sorted (in-place version):", inplace_array)