# Generated by ChatGPT: GPT-5 Thinking Mini on 12/4/2025 5:30 pm
# https://chatgpt.com/share/69380c70-ec14-8008-8bf1-84907f554353
from typing import Dict, List, Tuple
import heapq

Node = int
Weight = float
Graph = Dict[Node, List[Tuple[Node, Weight]]]

def dijkstra(graph: Graph, source: Node) -> Dict[Node, float]:
    """
    Compute shortest-path distances from source to every reachable node in a directed graph
    with non-negative edge weights using Dijkstra's algorithm and a min-heap (heapq).

    - `graph[u]` is a list of (v, w) meaning an edge u -> v with weight w (w >= 0).
    - Returns a dict `dist` mapping each reachable node `u` to the distance from `source` to `u`.
    - Nodes unreachable from `source` are omitted from the returned dict (you may treat them as having
    infinite distance, float('inf'), but they will not appear in the result).
    - Time complexity: O(E log V) where V is number of nodes and E is number of edges (using a min-heap).
    """
    dist: Dict[Node, float] = {}
    # min-heap of (distance, node)
    heap: List[Tuple[float, Node]] = []
    heapq.heappush(heap, (0.0, source))
    dist[source] = 0.0

    while heap:
        d_u, u = heapq.heappop(heap)
        # If we popped an outdated entry, skip it.
        if d_u != dist.get(u, float("inf")):
            continue

        for v, w in graph.get(u, []):
            if w < 0:
                raise ValueError("Dijkstra's algorithm requires non-negative edge weights")
            new_dist = d_u + w
            if new_dist < dist.get(v, float("inf")):
                dist[v] = new_dist
                heapq.heappush(heap, (new_dist, v))

    return dist
