// Generated by DeepSeek: V3.2 on 12/2/25 6:09 pm
// https://chat.deepseek.com/share/sx8dj08ibiyrw12a9f
pub fn quicksort(a: &mut [i32]) {
    if a.len() <= 1 {
        return;
    }
    let pivot_idx = partition(a);
    let (left, right) = a.split_at_mut(pivot_idx);
    quicksort(left);
    quicksort(&mut right[1..]);
}

fn partition(a: &mut [i32]) -> usize {
    let pivot = a[a.len() - 1];
    let mut i = 0;
    for j in 0..a.len() - 1 {
        if a[j] <= pivot {
            a.swap(i, j);
            i += 1;
        }
    }
    
    a.swap(i, a.len() - 1);
    i
}