// Generated by ChatGPT: GPT-5 Thinking Mini on 12/2/25 6:05 pm
// https://chatgpt.com/share/692f9bb2-027c-8008-8ca0-cd469715d098
pub fn quicksort(a: &mut [i32]) {
    fn sort(a: &mut [i32], lo: isize, hi: isize) {
        if lo >= hi {
            return;
        }
        let p = partition(a, lo, hi);
        sort(a, lo, p);
        sort(a, p + 1, hi);
    }
    fn partition(a: &mut [i32], lo: isize, hi: isize) -> isize {
        let mut i = lo - 1;
        let mut j = hi + 1;
        let mid = ((lo + hi) / 2) as usize;
        let pivot = a[mid];

        loop {
            loop {
                i += 1;
                if a[i as usize] >= pivot {
                    break;
                }
            }

            loop {
                j -= 1;
                if a[j as usize] <= pivot {
                    break;
                }
            }

            if i >= j {
                return j;
            }
            a.swap(i as usize, j as usize);
        }
    }
    let len = a.len();
    if len <= 1 {
        return;
    }
    sort(a, 0, (len - 1) as isize);
}
