// Generated by Google Gemini: 2.5 Pro on 12/2/25 6:10 pm 
// https://gemini.google.com/share/eba892e98d43
pub fn quicksort(a: &mut [i32]) {
    let len = a.len();
    if len < 2 {
        return;
    }
    let pivot_index = len / 2;
    a.swap(pivot_index, len - 1);
    let mut store_index = 0;
    for i in 0..len - 1 {
        if a[i] < a[len - 1] {
            a.swap(i, store_index);
            store_index += 1;
        }
    }
    a.swap(store_index, len - 1);
    quicksort(&mut a[0..store_index]);
    quicksort(&mut a[store_index + 1..len]);
}