// Generated by Claude: Sonnet 4.5 on 11/28/2025 4:18 pm
// https://claude.ai/public/artifacts/5a18de54-bdde-4437-ac47-43067989dadb
fn quicksort<T: Ord>(arr: &mut [T]) {
    if arr.len() <= 1 {
        return;
    }
    
    let pivot_idx = partition(arr);
    let (left, right) = arr.split_at_mut(pivot_idx);
    
    quicksort(left);
    quicksort(&mut right[1..]);
}

fn partition<T: Ord>(arr: &mut [T]) -> usize {
    let len = arr.len();
    let pivot_idx = len / 2;
    
    arr.swap(pivot_idx, len - 1);
    
    let mut i = 0;
    for j in 0..len - 1 {
        if arr[j] <= arr[len - 1] {
            arr.swap(i, j);
            i += 1;
        }
    }
    
    arr.swap(i, len - 1);
    i
}

fn main() {
    let mut numbers = vec![64, 34, 25, 12, 22, 11, 90, 88, 45, 50, 23];
    println!("Original: {:?}", numbers);
    
    quicksort(&mut numbers);
    println!("Sorted:   {:?}", numbers);
    
    // Works with other types too
    let mut strings = vec!["banana", "apple", "cherry", "date", "elderberry"];
    println!("\nOriginal strings: {:?}", strings);
    quicksort(&mut strings);
    println!("Sorted strings:   {:?}", strings);
}