// Generated by DeepSeek: V3.2 on 11/28/25 4:18 pm
// https://chat.deepseek.com/share/n703bm320rpr20tsf4
fn quicksort<T: Ord>(arr: &mut [T]) {
    if arr.len() <= 1 {
        return;
    }
    let pivot_index = partition(arr);
    let (left, right) = arr.split_at_mut(pivot_index);
    quicksort(left);
    quicksort(&mut right[1..]); // Exclude pivot
}

fn partition<T: Ord>(arr: &mut [T]) -> usize {
    let pivot_index = arr.len() - 1;
    let mut i = 0;
    for j in 0..pivot_index {
        if arr[j] <= arr[pivot_index] {
            arr.swap(i, j);
            i += 1;
        }
    }
    arr.swap(i, pivot_index);
    i
}

// Example usage:
fn main() {
    let mut numbers = vec![9, 4, 13, 2, 22, 17, 8, 5];
    println!("Before: {:?}", numbers);
    quicksort(&mut numbers);
    println!("After: {:?}", numbers);

    let mut strings = vec!["peach", "apple", "banana", "orange"];
    println!("Before: {:?}", strings);
    quicksort(&mut strings);
    println!("After: {:?}", strings);
}