// Generated by Claude: Sonnet 4.5 on 11/29/2025 9:33 pm
// https://claude.ai/share/448be1c1-4e40-4ad9-89e3-a828f67dca5f

pub fn quicksort(a: &mut [i32]) {
    if a.len() <= 1 {
        return;
    }
    let pivot_index = partition(a);
    let (left, right) = a.split_at_mut(pivot_index);
    quicksort(left);
    quicksort(&mut right[1..]);
}

fn partition(a: &mut [i32]) -> usize {
    let len = a.len();
    let pivot = a[len - 1];
    let mut i = 0;
    for j in 0..len - 1 {
        if a[j] <= pivot {
            a.swap(i, j);
            i += 1;
        }
    }
    a.swap(i, len - 1);
    i
}
```