// Generated by Google Gemini: 2.5 Pro on 11/28/25 4:18 pm 
// https://gemini.google.com/share/d8dd83ab270f
fn quicksort(arr: &mut [i32]) {
    let len = arr.len();
    if len < 2 {
        return;
    }

    let pivot_index = partition(arr);

    // Recursively sort elements before the pivot
    quicksort(&mut arr[0..pivot_index]);

    // Recursively sort elements after the pivot
    // We start at pivot_index + 1 because the pivot is already in the correct spot
    quicksort(&mut arr[pivot_index + 1..len]);
}

fn partition(arr: &mut [i32]) -> usize {
    let len = arr.len();
    let pivot_index = len - 1;
    let pivot = arr[pivot_index];
    
    let mut i = 0;

    for j in 0..len - 1 {
        if arr[j] <= pivot {
            arr.swap(i, j);
            i += 1;
        }
    }

    arr.swap(i, len - 1);
    i
}

fn main() {
    let mut numbers = [10, 80, 30, 90, 40, 50, 70];
    println!("Before: {:?}", numbers);
    
    quicksort(&mut numbers);
    
    println!("After:  {:?}", numbers);
}