// Generated by ChatGPT: GPT-5 Thinking Mini on 11/29/25 9:29 pm
// https://chatgpt.com/share/692bd5de-2548-8008-81be-2642f2024962
pub fn quicksort(a: &mut [i32]) {
    fn partition(slice: &mut [i32]) -> usize {
        let len = slice.len();
        let pivot_idx = len / 2;
        slice.swap(pivot_idx, len - 1);
        let pivot = slice[len - 1];
        let mut store = 0usize;
        for i in 0..(len - 1) {
            if slice[i] <= pivot {
                slice.swap(i, store);
                store += 1;
            }
        }
        slice.swap(store, len - 1);
        store
    }

    fn inner(slice: &mut [i32]) {
        if slice.len() <= 1 {
            return;
        }
        let p = partition(slice);
        inner(&mut slice[..p]);
        inner(&mut slice[p + 1..]);
    }

    inner(a);
}

