# Generated by Claude: Sonnet 4.5 on 12/2/2025 5:59 pm
# https://claude.ai/share/24e8d61b-6451-411d-b2a3-bf5613086637
def quicksort(a: list[int]) -> None:
    def partition(low, high):
        mid = (low + high) // 2
        a[mid], a[high] = a[high], a[mid]
        pivot = a[high]
        i = low - 1
        for j in range(low, high):
            if a[j] <= pivot:
                i += 1
                a[i], a[j] = a[j], a[i]
        a[i + 1], a[high] = a[high], a[i + 1]
        return i + 1
    
    def quicksort_helper(low, high):
        if low < high:
            pi = partition(low, high)
            quicksort_helper(low, pi - 1)
            quicksort_helper(pi + 1, high)
    
    if len(a) > 1:
        quicksort_helper(0, len(a) - 1)