# Generated by ChatGPT: GPT-5 Thinking Mini on 12/4/2025 5:19 pm
# https://chatgpt.com/share/693809de-9954-8008-95e0-b89270cd36d2
from typing import Dict, List, Tuple
import heapq

Node = int
Weight = float
Graph = Dict[Node, List[Tuple[Node, Weight]]]

def dijkstra(graph: Graph, source: Node) -> Dict[Node, float]:
    """
    Compute shortest-path distances from source to every reachable node using Dijkstra's algorithm.

    - `graph[u]` is a list of (v, w) edges meaning an edge u -> v with weight w (w >= 0).
    - Returns a dict `dist` mapping nodes reachable from `source` to their distance (float).
    - Nodes unreachable from `source` are omitted from the returned dict.
    The `source` itself is always present with distance 0.0.
    - Uses a min-heap (heapq). Time complexity: O(E log V).
    """
    dist: Dict[Node, float] = {source: 0.0}
    heap: List[Tuple[float, Node]] = [(0.0, source)]

    while heap:
        d_u, u = heapq.heappop(heap)
        # If we have already found a better path to u, skip this entry.
        if d_u > dist.get(u, float("inf")):
            continue

        for v, w in graph.get(u, []):
            if w < 0:
                raise ValueError("Dijkstra's algorithm requires non-negative edge weights")
            new_d = d_u + float(w)
            if new_d < dist.get(v, float("inf")):
                dist[v] = new_d
                heapq.heappush(heap, (new_d, v))

    return dist