# Generated by Claude: Sonnet 4.5 on 12/4/2025 5:21 pm
# https://claude.ai/share/038515f7-3b3a-4f78-a55e-13ede8df7004
from typing import Dict, List, Tuple
import heapq

Node = int
Weight = float
Graph = Dict[Node, List[Tuple[Node, Weight]]]

def dijkstra(graph: Graph, source: Node) -> Dict[Node, float]:
    """
    Compute the shortest path distance from `source` to every reachable node
    in a directed graph with non-negative edge weights.
    
    Args:
        graph: Adjacency list where graph[u] is a list of (v, w) tuples
               representing edges u -> v with weight w.
        source: The starting node.
    
    Returns:
        A dict mapping each reachable node to its shortest distance from source.
        Unreachable nodes are omitted from the result.
    
    Time complexity: O(E log V) where E is the number of edges and V is the number of vertices.
    """
    dist = {source: 0.0}
    pq = [(0.0, source)]
    
    while pq:
        current_dist, u = heapq.heappop(pq)
        
        # Skip if we've already found a better path
        if current_dist > dist.get(u, float('inf')):
            continue
        
        # Explore neighbors
        if u in graph:
            for v, weight in graph[u]:
                new_dist = current_dist + weight
                
                # If we found a shorter path to v
                if new_dist < dist.get(v, float('inf')):
                    dist[v] = new_dist
                    heapq.heappush(pq, (new_dist, v))
    
    return dist