// Generated by Google Gemini: 2.5 Pro on 11/28/25 4:18 pm 
// https://gemini.google.com/share/fe1c85f1e112
pub fn quicksort(a: &mut [i32]) { 
    fn partition(a: &mut [i32]) -> usize { let len = a.len(); 
        let pivot_idx = len / 2; a.swap(pivot_idx, len - 1); 
        let mut i = 0; 
        for j in 0..len - 1 { 
            if a[j] <= a[len - 1] { 
                a.swap(i, j); i += 1; 
            } 
        } 
        a.swap(i, len - 1); i 
    }

    if a.len() <= 1 {
        return;
    }
    let p = partition(a);
    let (left, right) = a.split_at_mut(p);
    quicksort(left);
    quicksort(&mut right[1..]);
}