# Generated by ChatGPT: GPT-5 Thinking Mini on 11/29/25 9:05 pm
# https://chatgpt.com/share/692bd07f-93c4-8008-9c14-9899b568d4ea
def quicksort(a: list[int]) -> None:
    def _quicksort(lo: int, hi: int) -> None:
        if lo >= hi:
            return
        pivot = a[(lo + hi) // 2]
        i, j = lo, hi
        while i <= j:
            while a[i] < pivot:
                i += 1
            while a[j] > pivot:
                j -= 1
            if i <= j:
                a[i], a[j] = a[j], a[i]
                i += 1
                j -= 1
        if lo < j:
            _quicksort(lo, j)
        if i < hi:
            _quicksort(i, hi)
    if a:
        _quicksort(0, len(a) - 1)