# Generated by ChatGPT: GPT-5 Thinking Mini on 12/3/25 8:12 pm
# https://chatgpt.com/share/69310acc-88dc-8008-bf23-3a4271f4a517
from typing import Dict, List, Tuple
import heapq

Node = int
Weight = float
Graph = Dict[Node, List[Tuple[Node, Weight]]]

def dijkstra(graph: Graph, source: Node) -> Dict[Node, float]:
    """
    Compute shortest-path distances from source to every node mentioned in graph
    (either as a key or as a target in an adjacency list) in a directed graph with
    non-negative edge weights using Dijkstra's algorithm and a min-heap.

    Return:
        A dict `dist` mapping each node present in the graph to its shortest distance
        from `source`. Nodes unreachable from `source` are included with distance
        float('inf').
    """
    # Collect all nodes that appear either as keys or targets
    nodes = set(graph.keys())
    for u_adj in graph.values():
        for v, _ in u_adj:
            nodes.add(v)
    nodes.add(source)

    # Initialize distances
    dist: Dict[Node, float] = {n: float("inf") for n in nodes}
    dist[source] = 0.0

    # Min-heap of (distance, node)
    heap: List[Tuple[float, Node]] = [(0.0, source)]

    while heap:
        d_u, u = heapq.heappop(heap)
        # If we popped an outdated entry, skip
        if d_u > dist[u]:
            continue
        # Iterate neighbors (if u has no outgoing edges, graph.get(u, []) yields empty list)
        for v, w in graph.get(u, []):
            if w < 0:
                # Dijkstra requires non-negative weights; skip negative edges defensively
                continue
            new_d = d_u + w
            if new_d < dist[v]:
                dist[v] = new_d
                heapq.heappush(heap, (new_d, v))

    return dist