# Generated by DeepSeek: V3.2 on 12/3/25 8:10 pm
# https://chat.deepseek.com/share/7ei927q7aw6puvwigz
from typing import Dict, List, Tuple
import heapq

Node = int
Weight = float
Graph = Dict[Node, List[Tuple[Node, Weight]]]

def dijkstra(graph: Graph, source: Node) -> Dict[Node, float]:
    """
    Compute the shortest path distance from `source` to every reachable node
    in a directed graph with non-negative edge weights.

    - `graph[u]` is a list of (v, w) edges meaning an edge u -> v with weight w.
    - Return a dict `dist` where `dist[u]` is the distance from `source` to u.
    - Nodes unreachable from `source` are omitted from the result.
    """
    # Initialize distances with source at 0
    dist = {source: 0.0}
    
    # Min-heap priority queue: (distance, node)
    heap = [(0.0, source)]
    
    while heap:
        current_dist, u = heapq.heappop(heap)
        
        # Skip if we've found a better path to u already
        if current_dist > dist.get(u, float('inf')):
            continue
        
        # Explore neighbors
        for v, w in graph.get(u, []):
            new_dist = current_dist + w
            if new_dist < dist.get(v, float('inf')):
                dist[v] = new_dist
                heapq.heappush(heap, (new_dist, v))
    
    return dist