# Generated by Claude: Sonnet 4.5 on 12/3/2025 8:16 pm
# https://claude.ai/share/aaf1974a-5953-4b29-bc42-a95b86587db2
from typing import Dict, List, Tuple
import heapq

Node = int
Weight = float
Graph = Dict[Node, List[Tuple[Node, Weight]]]

def dijkstra(graph: Graph, source: Node) -> Dict[Node, float]:
    """
    Compute the shortest path distance from `source` to every reachable node
    in a directed graph with non-negative edge weights.
    
    Args:
        graph: Adjacency list where graph[u] = [(v, w), ...] represents edges u -> v with weight w
        source: Starting node
    
    Returns:
        Dictionary mapping each reachable node to its shortest distance from source.
        Unreachable nodes are omitted from the result.
    
    Time complexity: O(E log V) where E is the number of edges and V is the number of nodes.
    """
    dist = {source: 0.0}
    pq = [(0.0, source)]
    
    while pq:
        current_dist, u = heapq.heappop(pq)
        
        if current_dist > dist.get(u, float('inf')):
            continue
        
        if u not in graph:
            continue
        
        for v, weight in graph[u]:
            new_dist = current_dist + weight
            
            if new_dist < dist.get(v, float('inf')):
                dist[v] = new_dist
                heapq.heappush(pq, (new_dist, v))
    
    return dist