// Generated by Claude: Sonnet 4.5 on 12/3/2025 9:31 pm
// https://claude.ai/share/4fd27027-f40c-42f4-82d8-eea122c5ed0b
use std::collections::{BinaryHeap, HashMap};
use std::cmp::Reverse;

pub type Node = usize;
pub type Weight = f64;
pub type Graph = HashMap<Node, Vec<(Node, Weight)>>;

#[derive(Copy, Clone, PartialEq)]
struct State {
    cost: Weight,
    node: Node,
}

impl Eq for State {}

impl PartialOrd for State {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for State {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.cost.partial_cmp(&other.cost).unwrap_or(std::cmp::Ordering::Equal)
    }
}

// Returns shortest distances from source to all reachable nodes.
// Unreachable nodes are omitted from the result.
pub fn dijkstra(graph: &Graph, source: Node) -> HashMap<Node, Weight> {
    let mut dist: HashMap<Node, Weight> = HashMap::new();
    let mut heap = BinaryHeap::new();

    dist.insert(source, 0.0);
    heap.push(Reverse(State { cost: 0.0, node: source }));

    while let Some(Reverse(State { cost, node })) = heap.pop() {
        if let Some(&current_dist) = dist.get(&node) {
            if cost > current_dist {
                continue;
            }
        }

        if let Some(neighbors) = graph.get(&node) {
            for &(neighbor, weight) in neighbors {
                let next_cost = cost + weight;
                let is_shorter = dist.get(&neighbor).map_or(true, |&d| next_cost < d);

                if is_shorter {
                    dist.insert(neighbor, next_cost);
                    heap.push(Reverse(State { cost: next_cost, node: neighbor }));
                }
            }
        }
    }

    dist
}